SELECT DEPARTMENT, COUNT(*)
FROM Employee
GROUP BY DEPARTMENT;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM Employee
WHERE MANAGER = NULL
GROUP BY EMPLOYEE_ID;

SELECT EMPLOYEE_REF_ID, sum(INCENTIVE_AMOUNT)
FROM Incentives
GROUP BY EMPLOYEE_REF_ID;

SELECT max(total), INCENTIVE_DATE
FROM Incentives
WHERE Total = (SELECT sum(INCENTIVE_AMOUNT)
        FROM Incentives
        GROUP BY sum(INCENTIVE_AMOUNT) DESC;)
